package kr.co.MyPick_server.DTO.chat.ChatMessage;

import lombok.Data;

import java.util.List;

/**
 * ChatMessageDTO is a Data Transfer Object (DTO) used to store responses generated by an AI.
 * This class encapsulates the AI's responses in various forms, including a detailed answer,
 * a concise summary, and a list of related games or items mentioned within the answer.
 */
@Data
public class ChatMessageDTO {
    /**
     * The complete text of the answer generated by the AI. This field contains the full response
     * from the AI to a query or conversation prompt within the chat.
     */
    private String answer;

    /**
     * A summary of the AI's answer. This is a concise version of the response that highlights
     * the key points or conclusions derived from the AI's full text, useful for quick overviews.
     */
    private String summary;

    /**
     * A list of games or other items discussed within the AI's answer. Each item in the list is
     * represented by a ChatMessageListInfoDTO, which includes details like the title and creator
     * of the game or item.
     */
    private List<ChatMessageListInfoDTO> list;
}
